#!/usr/bin/env bash

versions=(51 52 53 54 jit)
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Passing plume test for all lua version. (dev version)" #for error location
for v in "${versions[@]}"
do
    printf "\tlua%s : " "$v"
    eval "lua$v $script_dir/tests/test.lua --run --fullog --plume $script_dir/main --test $script_dir/tests/test.plume"
done

echo "Passing plume test for all lua version. (dist version)"
for v in "${versions[@]}"
do
    printf "\tlua%s : " "$v"
    eval "lua$v $script_dir/tests/test.lua --run --log --plume $script_dir/dist/plume --test $script_dir/tests/test.plume"
done