#!/usr/bin/env bash

versions=(51 52 53 54 jit)
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cd $script_dir

echo "Passing wings test for all lua version. (dev version)" #for error location
for v in "${versions[@]}"
do
    printf "\tlua%s : " "$v"
    eval "lua$v tests/test.lua --run --fullog --wings wings --test tests/"
done

echo "Passing wings test for all lua version. (dist version)"
for v in "${versions[@]}"
do
    printf "\tlua%s : " "$v"
    eval "lua$v tests/test.lua --run --log --wings dist/wings --test tests/"
done