#!/usr/bin/env bash

versions=(51 52 53 54 jit)

echo "Passing plume test for all lua version."

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

for v in "${versions[@]}"
do
    printf "\tlua%s : " "$v"
    eval "lua$v $script_dir/tests/test.lua --run --fullog --plume $script_dir/plume --test $script_dir/tests/test.plume"
    eval "lua$v $script_dir/tests/test.lua --run --fullog --plume $script_dir/dist/plume --test $script_dir/tests/test.plume"
done